<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\WiFiCamera;

class WiFiCameraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cameras = [
            [
                'slug' => 'c6n',
                'name' => 'C6N',
                'brand' => 'EZVIZ',
                'brand_logo' => null,
                'subtitle' => 'Smart Pan & Tilt Indoor Wifi Camera',
                'price' => 1065000,
                'original_price' => null,
                'main_image' => 'https://via.placeholder.com/400x400/ffffff/667eea?text=C6N',
                'gallery_images' => [
                    'https://via.placeholder.com/400x400/ffffff/667eea?text=C6N+Front',
                    'https://via.placeholder.com/400x400/ffffff/667eea?text=C6N+Side',
                    'https://via.placeholder.com/400x400/ffffff/667eea?text=C6N+Back',
                ],
                'resolutions' => [
                    ['label' => '2MP', 'active' => true],
                    ['label' => '4MP', 'active' => false],
                ],
                'specifications' => [
                    '2MP 1080P Resolution',
                    'Wifi 2.4 Ghz',
                    'MicroSD Slot (Up to 256GB)',
                    'Motion Detection',
                    'Motorized Pan & Tilt 360° View',
                    'Smart Night Vision with Smart IR (Up to 10m)',
                    'Two-way Talk Audio',
                    'Smart Tracking',
                    'Sleep Mode for Privacy Protection',
                ],
                'package_includes' => [
                    '1 Kamera C6N 2MP',
                    'Memory Card 32GB',
                    'Kabel Power 5m',
                    'Training Cloud',
                    'Terminal 1 Lubang 1 Unit',
                    'Jasa Pasang & Konfigurasi',
                    'Steker 1 Unit',
                ],
                'status' => 'active',
                'is_featured' => true,
                'stock' => 15,
                'sold' => 5,
                'sku' => 'EZVIZ-C6N-001',
            ],
            [
                'slug' => 'h8c',
                'name' => 'H8C',
                'brand' => 'EZVIZ',
                'brand_logo' => null,
                'subtitle' => 'Smart Wifi Pan & Tilt Outdoor Camera',
                'price' => 1699000,
                'original_price' => 1899000,
                'main_image' => 'https://via.placeholder.com/400x400/ffffff/11998e?text=H8C',
                'gallery_images' => [
                    'https://via.placeholder.com/400x400/ffffff/11998e?text=H8C+Front',
                    'https://via.placeholder.com/400x400/ffffff/11998e?text=H8C+Side',
                    'https://via.placeholder.com/400x400/ffffff/11998e?text=H8C+Back',
                ],
                'resolutions' => [
                    ['label' => '2MP', 'active' => true],
                ],
                'specifications' => [
                    '2MP 1080P Resolution',
                    'Wifi 2.4 Ghz & 5 Ghz',
                    'MicroSD Slot (Up to 256GB)',
                    'Motion Detection & AI Human Detection',
                    'Motorized Pan & Tilt 360° View',
                    'Color Night Vision',
                    'Two-way Talk Audio',
                    'Weatherproof IP67',
                    'Active Defense with Siren & Strobe Light',
                ],
                'package_includes' => [
                    '1 Kamera H8C 2MP',
                    'Memory Card 64GB',
                    'Kabel Power 10m',
                    'Training Cloud',
                    'Terminal Outdoor 1 Unit',
                    'Jasa Pasang & Konfigurasi',
                    'Steker Outdoor 1 Unit',
                ],
                'status' => 'active',
                'is_featured' => true,
                'stock' => 8,
                'sold' => 12,
                'sku' => 'EZVIZ-H8C-001',
            ],
            [
                'slug' => 'ranger-a1',
                'name' => 'Ranger A1',
                'brand' => 'IMOU',
                'brand_logo' => null,
                'subtitle' => 'Smart Wifi Pan & Tilt Indoor Camera',
                'price' => 1329000,
                'original_price' => null,
                'main_image' => 'https://via.placeholder.com/400x400/ffffff/ee0979?text=Ranger+A1',
                'gallery_images' => [
                    'https://via.placeholder.com/400x400/ffffff/ee0979?text=Ranger+Front',
                    'https://via.placeholder.com/400x400/ffffff/ee0979?text=Ranger+Side',
                    'https://via.placeholder.com/400x400/ffffff/ee0979?text=Ranger+Back',
                ],
                'resolutions' => [
                    ['label' => '3MP', 'active' => true],
                ],
                'specifications' => [
                    '3MP 2K Resolution',
                    'Wifi 2.4 Ghz',
                    'MicroSD Slot (Up to 256GB)',
                    'AI Human Detection',
                    'Motorized Pan & Tilt 360° View',
                    'Smart Night Vision (Up to 10m)',
                    'Two-way Talk Audio',
                    'Smart Tracking',
                    'Privacy Mode',
                ],
                'package_includes' => [
                    '1 Kamera Ranger A1 3MP',
                    'Memory Card 32GB',
                    'Kabel Power 5m',
                    'Training Cloud',
                    'Terminal 1 Lubang 1 Unit',
                    'Jasa Pasang & Konfigurasi',
                    'Steker 1 Unit',
                ],
                'status' => 'active',
                'is_featured' => false,
                'stock' => 20,
                'sold' => 3,
                'sku' => 'IMOU-RA1-001',
            ],
            [
                'slug' => 'cruiser-sc',
                'name' => 'Cruiser SC',
                'brand' => 'IMOU',
                'brand_logo' => null,
                'subtitle' => 'Smart Home Pan & Tilt Outdoor Wifi Camera',
                'price' => 1879000,
                'original_price' => null,
                'main_image' => 'https://via.placeholder.com/400x400/ffffff/7f00ff?text=Cruiser+SC',
                'gallery_images' => [
                    'https://via.placeholder.com/400x400/ffffff/7f00ff?text=Cruiser+Front',
                    'https://via.placeholder.com/400x400/ffffff/7f00ff?text=Cruiser+Side',
                    'https://via.placeholder.com/400x400/ffffff/7f00ff?text=Cruiser+Back',
                ],
                'resolutions' => [
                    ['label' => '5MP', 'active' => true],
                ],
                'specifications' => [
                    '5MP 3K Resolution',
                    'Wifi 2.4 Ghz & 5 Ghz',
                    'MicroSD Slot (Up to 256GB)',
                    'AI Human & Vehicle Detection',
                    'Motorized Pan & Tilt 360° View',
                    'Full Color Night Vision',
                    'Two-way Talk Audio',
                    'Active Deterrence with Siren',
                    'Weatherproof IP66',
                ],
                'package_includes' => [
                    '1 Kamera Cruiser SC 5MP',
                    'Memory Card 64GB',
                    'Kabel Power 10m',
                    'Training Cloud',
                    'Terminal Outdoor 1 Unit',
                    'Jasa Pasang & Konfigurasi',
                    'Steker Outdoor 1 Unit',
                ],
                'status' => 'active',
                'is_featured' => false,
                'stock' => 10,
                'sold' => 8,
                'sku' => 'IMOU-CSC-001',
            ],
            [
                'slug' => 'c3w-pro',
                'name' => 'C3W Pro',
                'brand' => 'EZVIZ',
                'brand_logo' => null,
                'subtitle' => 'Color Night Vision Outdoor Camera',
                'price' => 1450000,
                'original_price' => null,
                'main_image' => 'https://via.placeholder.com/400x400/ffffff/2193b0?text=C3W+Pro',
                'gallery_images' => [
                    'https://via.placeholder.com/400x400/ffffff/2193b0?text=C3W+Front',
                    'https://via.placeholder.com/400x400/ffffff/2193b0?text=C3W+Side',
                    'https://via.placeholder.com/400x400/ffffff/2193b0?text=C3W+Back',
                ],
                'resolutions' => [
                    ['label' => '2MP', 'active' => true],
                ],
                'specifications' => [
                    '2MP 1080P Resolution',
                    'Wifi 2.4 Ghz',
                    'MicroSD Slot (Up to 256GB)',
                    'Smart Motion Detection',
                    'Fixed Lens',
                    'Color Night Vision',
                    'Two-way Audio',
                    'Weatherproof IP67',
                    'Smart Tracking',
                ],
                'package_includes' => [
                    '1 Kamera C3W Pro 2MP',
                    'Memory Card 32GB',
                    'Kabel Power 5m',
                    'Terminal Outdoor 1 Unit',
                    'Jasa Pasang & Konfigurasi',
                    'Steker 1 Unit',
                ],
                'status' => 'active',
                'is_featured' => false,
                'stock' => 12,
                'sold' => 6,
                'sku' => 'EZVIZ-C3W-001',
            ],
            [
                'slug' => 'bullet-2e',
                'name' => 'Bullet 2E',
                'brand' => 'IMOU',
                'brand_logo' => null,
                'subtitle' => 'Outdoor Bullet WiFi Camera',
                'price' => 899000,
                'original_price' => 1099000,
                'main_image' => 'https://via.placeholder.com/400x400/ffffff/eb3349?text=Bullet+2E',
                'gallery_images' => [
                    'https://via.placeholder.com/400x400/ffffff/eb3349?text=Bullet+Front',
                    'https://via.placeholder.com/400x400/ffffff/eb3349?text=Bullet+Side',
                    'https://via.placeholder.com/400x400/ffffff/eb3349?text=Bullet+Back',
                ],
                'resolutions' => [
                    ['label' => '2MP', 'active' => true],
                ],
                'specifications' => [
                    '2MP 1080P Resolution',
                    'Wifi 2.4 Ghz',
                    'MicroSD Slot (Up to 256GB)',
                    'Motion Detection',
                    'Fixed Bullet Design',
                    'Night Vision 30m',
                    'Weatherproof IP67',
                    'Smart Notification',
                ],
                'package_includes' => [
                    '1 Kamera Bullet 2E 2MP',
                    'Memory Card 32GB',
                    'Kabel Power 5m',
                    'Terminal Outdoor 1 Unit',
                    'Jasa Pasang & Konfigurasi',
                    'Steker 1 Unit',
                ],
                'status' => 'active',
                'is_featured' => false,
                'stock' => 25,
                'sold' => 15,
                'sku' => 'IMOU-B2E-001',
            ],
            [
                'slug' => 'tapo-c200',
                'name' => 'Tapo C200',
                'brand' => 'TP-LINK',
                'brand_logo' => null,
                'subtitle' => 'Pan/Tilt WiFi Camera',
                'price' => 450000,
                'original_price' => 599000,
                'main_image' => 'https://via.placeholder.com/400x400/ffffff/f39c12?text=Tapo+C200',
                'gallery_images' => [
                    'https://via.placeholder.com/400x400/ffffff/f39c12?text=Tapo+Front',
                    'https://via.placeholder.com/400x400/ffffff/f39c12?text=Tapo+Side',
                    'https://via.placeholder.com/400x400/ffffff/f39c12?text=Tapo+Back',
                ],
                'resolutions' => [
                    ['label' => '2MP', 'active' => true],
                ],
                'specifications' => [
                    '2MP 1080P Resolution',
                    'Wifi 2.4 Ghz',
                    'MicroSD Slot (Up to 128GB)',
                    'Motion Detection',
                    'Pan & Tilt 360°',
                    'Night Vision 9m',
                    'Two-Way Audio',
                    'Smart Notification',
                ],
                'package_includes' => [
                    '1 Kamera Tapo C200 2MP',
                    'Kabel Power 3m',
                    'Terminal 1 Lubang 1 Unit',
                    'Panduan Setup',
                    'Steker 1 Unit',
                ],
                'status' => 'active',
                'is_featured' => true,
                'stock' => 30,
                'sold' => 25,
                'sku' => 'TP-LINK-TC200-001',
            ],
        ];

        foreach ($cameras as $camera) {
            WiFiCamera::create($camera);
        }

        $this->command->info('✅ ' . count($cameras) . ' WiFi Cameras seeded successfully!');
    }
}